export enum EnrollmentEligibilityReason {
  ELIGIBLE = 'ELIGIBLE',
  ALREADY_ENROLLED = 'ALREADY_ENROLLED',
  ANOTHER_ACTIVE_BATCH = 'ANOTHER_ACTIVE_BATCH',
  BATCH_FULL = 'BATCH_FULL',
  ENROLLMENT_CLOSED = 'ENROLLMENT_CLOSED',
  BATCH_NOT_FOUND = 'BATCH_NOT_FOUND',
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  INVALID_BATCH = 'INVALID_BATCH',
  CHECK_FAILED = 'CHECK_FAILED'
}
