export enum CourseCategory {
  SCIENCE = 'SCIENCE',
  TECHNOLOGY = 'TECHNOLOGY',
  ENGINEERING = 'ENGINEERING',
  MATHEMATICS = 'MATHEMATICS',
  BUSINESS = 'BUSINESS',
  ARTS = 'ARTS',
  LANGUAGE = 'LANGUAGE',
  OTHER = 'OTHER',
}
