export enum FeedbackEligibilityReason {
  ELIGIBLE = 'ELIGIBLE',
  NOT_STUDENT = 'NOT_STUDENT',
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  ALREADY_SUBMITTED = 'ALREADY_SUBMITTED',
  NOT_ENROLLED = 'NOT_ENROLLED',
}
