export enum SubmissionEligibilityReason {
  ELIGIBLE = 'ELIGIBLE',
  LATE_SUBMISSION_NOT_ALLOWED = 'LATE_SUBMISSION_NOT_ALLOWED',
  MAX_ATTEMPTS_REACHED = 'MAX_ATTEMPTS_REACHED',
  RESUBMISSION_NOT_ALLOWED = 'RESUBMISSION_NOT_ALLOWED'
}
