name: GitHub Release

on:
  push:
    branches:
      - chore/CI-CD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch current and previous commit

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get current package version
        id: package-version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Get previous package version
        id: previous-version
        run: |
          PREV_VERSION=$(git show HEAD^:package.json | jq -r .version)
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_OUTPUT

      - name: Check if version changed
        id: version-check
        run: |
          if [ "${{ steps.package-version.outputs.VERSION }}" != "${{ steps.previous-version.outputs.PREV_VERSION }}" ]; then
            echo "VERSION_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Zip release
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        run: |
          cd dist
          zip -r tuition-to-all-client-v${{ steps.package-version.outputs.VERSION }}.zip tuition-to-all-client

      - name: Create GitHub Release
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.VERSION }}
          release_name: Release v${{ steps.package-version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: |
            Release v${{ steps.package-version.outputs.VERSION }}
            - TuitionToAll Client Angular project
            - Auto-generated by GitHub Actions

      - name: Upload Release Asset
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/tuition-to-all-client-v${{ steps.package-version.outputs.VERSION }}.zip
          asset_name: tuition-to-all-client-v${{ steps.package-version.outputs.VERSION }}.zip
          asset_content_type: application/zip
